// Generated by scripts/sync-changelog.mjs — do not edit by hand.
export const releases: Record<string, { version: string; date: string }> = {
  'expo-devtools': { version: '2.5.4', date: '2 September 2026' },
};
