// Generated by scripts/sync-changelog.mjs — do not edit by hand.
export const releases: Record<string, { version: string; date: string }> = {
  'expo-devtools': { version: '3.0.0', date: '14 September 2026' },
  'react-pretty-print': { version: '0.1.0', date: '10 September 2026' },
};
